/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_borne.vue;
import javax.swing.GroupLayout.Alignment;

import gestion_borne.AlgorithmeBorne;

import java.sql.SQLException;

import javax.swing.GroupLayout;



/**
 *
 * @author Anaelle Donfack
 */
public class TraficVue  extends javax.swing.JDialog  {
	
	AlgorithmeBorne algo = new AlgorithmeBorne();

	/**
	 * Creates new form TraficVue
	 */
	public TraficVue(java.awt.Frame parent, boolean modal) throws ClassNotFoundException, SQLException {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		btnCancel = new javax.swing.JButton();
		btnValider = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("TRAFIC CIRCULATION");

		btnCancel.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
		btnCancel.setText("annuler");
		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelActionPerformed(evt);
			}
		});

		btnValider.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
		btnValider.setText("Valider");
		btnValider.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnValiderActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(183, Short.MAX_VALUE)
						.addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap())
				);

		jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
		jLabel1.setText("Nom");

		jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
		jLabel2.setText("Prenom :"+algo.getPlacesOccupees());

		jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
		jLabel3.setText("Login");

		jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
		jLabel4.setText("Password");

		jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
		jLabel5.setText("Profil");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(jLabel2)
										.addComponent(jLabel1)
										.addComponent(jLabel3))
								.addComponent(jLabel4)
								.addComponent(jLabel5))
						.addGap(370))
				);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1)
						.addGap(18)
						.addComponent(jLabel2)
						.addGap(18)
						.addComponent(jLabel3)
						.addGap(18)
						.addComponent(jLabel4)
						.addGap(18)
						.addComponent(jLabel5)
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		jPanel2.setLayout(jPanel2Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(18, 18, 18)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				);

		pack();
	}// </editor-fold>                        

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
		// TODO add your handling code here:
		this.dispose();
	}                                         

	private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {                                           

	}                                          


	// Variables declaration - do not modify                     
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnValider;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	// End of variables declaration                   
}
